### ISSUE TITLE
Unable to check more than on match type when creating a new token for a rule.

### ISSUE THREAD

**Issue by TravelingGeek** [thepaperpilot/Gift-Exchange-2#1]
By default Names is checked.  I can't check any others.

Note:  Once the token is created, I can go back and check more than one.

**Comment by thepaperpilot** [comment]
![selection_035](https://cloud.githubusercontent.com/assets/3683148/19916865/0a0592d0-a08c-11e6-8376-754d038e1ff6.png)

Can't Reproduce
