### ISSUE TITLE
Participant should have first and last name

### ISSUE THREAD

**Issue by TravelingGeek** [thepaperpilot/Gift-Exchange-2#2]
I have two participants with the same first name (Jay).  I can't tell them apart in the participant list.

**Comment by thepaperpilot** [comment]
Maybe the term "family" is confusing, but that's a way of grouping people together for rule making. It does not actually refer to a person's family name. Their last name would go in the "name" field, probably after the first name and a space.

**Comment by thepaperpilot** [comment]
Renamed "family" to "class" in 2a90504. That should make it more clear.

**Comment by TravelingGeek** [comment]
I probably would have gone with Group or "Family / Group" but class will
work for those that know what it's doing.
