### ISSUE TITLE
Participant list only shows who they are giving to.... It should also show who they are receiving from.

### ISSUE THREAD

**Issue by TravelingGeek** [thepaperpilot/Gift-Exchange-2#7]

**Comment by thepaperpilot** [comment]
Maybe it can be clearer in the UI, but clicking on someone's name shows both who they are giving to as well as receiving from

**Comment by thepaperpilot** [comment]
Fixed in 82f29296b8b0720be89884f4a4f0be2b3ef2e02f by adding a face icon to each of the rows in the participant list, which I think makes it "feel" more like it can be expanded for more info.
